web:
  build: ../web
  restart: always
  mem_limit: 128m
  ports:
    - "80"
  environment:
    SERVICE_80_NAME: ${POD_NAME}/http
    SERVICE_443_NAME: ${POD_NAME}/https
  volumes_from:
    - data
  links:
    - mysql

mysql:
  image: mysql:5.6
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: wordpress
    MYSQL_DATABASE: wordpress
    SERVICE_IGNORE: ignore
  volumes_from:
    - data

data:
  build: ../data
  command: tail -f /dev/null
  restart: always
  environment:
    SERVICE_IGNORE: ignore
  volumes:
    - ${DATA_LOCATION}/www:/var/www/wordpress
    - ${DATA_LOCATION}/db:/var/lib/mysql
    - ${DATA_LOCATION}/db:/config
