web:
  build: ../web
  restart: always
  environment:
    SERVICE_80_NAME: ${POD_NAME}/http
    SERVICE_443_NAME: ${POD_NAME}/https
  volumes_from:
    - data
  links:
    - mysql

mysql:
    build: ../mysql
    dockerfile: production
    restart: always
    environment:
      DATABASE_NAME: ${POD_NAME}
      SERVICE_IGNORE: ignore
    external_links:
      - paas_mysql_api
      - paas_mysql_service
    volumes_from:
      - data

data:
  build: ../data
  command: tail -f /dev/null
  restart: always
  environment:
    SERVICE_IGNORE: ignore
  volumes:
    - ${DATA_LOCATION}/www:/var/www/wordpress
    - ${DATA_LOCATION}/db:/var/lib/mysql
    - ${DATA_LOCATION}/db:/config
